<a href="https://colab.research.google.com/github/Pilarppk/SIM_YAC_PARRALES_UPSE2023/blob/main/Comparacion%20de%20metdos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np
import math


In [73]:
L=10000 #distancia del yacimiento
dx=2500 #distancia eentre nodos
Tiempo= 100000 #tiempo total
DT=1 #delta tiempo
K=50 #permeabilidad MD
Por=0.2 #porosidad
vis=1 # viscosidad en ceentipoy
Beta=1
Comptotal=1**(-6) #psi-1
A=200000 #area ft**2


In [74]:
Alpha=K/(vis*Por*Comptotal) 
Alpha
Eta=(Alpha*DT)/(dx**2)
Eta

4e-05

In [75]:
#esquema explicito
def Presdt(P0,P1,P2,Eta):
 Pdt=P1+Eta*(P0-2*P1+P2)
 return(Pdt)
Pexplicita=np.zeros((Tiempo//DT,L//dx))

In [83]:
#condiciones iniciales
Pyac=1000
Piz=2000
Pder=0
Pin=np.ones(L//dx)
Pres=np.zeros(L//dx)
Pin=Pin*Pyac
Pin[0]=Piz
Pin[len(Pin)-1]=Pder
Pin

array([2000., 1000., 1000.,    0.])

In [91]:

t=DT
Pexplicita[0]=Pin
Pexplicita.shape
while t<Tiempo:
  for i in range(0,len(Pin)-1):
    if i==0:
      Pres[i]=Pin[0]
    elif i==len(Pin)-1:
      Pres[i]=Pin[len(Pin)-1]
    else:
      Pres[i]=Presdt(Pin[i-1],Pin[i],Pin[i+1],Eta)
  Pexplicita[t/DT]=Pres
  t=t+DT
  Pin=Pres





IndexError: ignored

In [38]:
#esquema implicito
Pexplicita=np.zeros((Tiempo//DT,L//dx))
Pimplicita=np.zeros((Tiempo//DT,L//dx))
Pin=np.ones(L//dx)
Pres=np.zeros(L//dx)
Pin=Pin*Pyac
Pin[0]=Piz
Pin[len(Pin)-1]=Pder
N=L//dx
Matriz_resolution=np.zeros([N-2,N-2])

In [33]:
for i in range(N-2):
  Matriz_resolution[i,i]=1+2*Eta
  if i>0:
    Matriz_resolution[i,i-1]=-Eta
  if i<(N-3):
    Matriz_resolution[i,i+1]=-Eta



In [65]:
Pcal=np.zeros((N-2)) #guardar resultados


In [68]:
Pcal=np.linal.solve(Matriz_resolution,Pin[1:-1])

AttributeError: ignored

In [43]:
Pcal

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
Pres=np.concatenate(([Piz],Pcal,[Pder])) #tomar varios valores y juntarlos(Pfrontera)
Pres

array([2000.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.])

In [44]:
#presion implicita
Pimplicita[0]=Pin
t=DT
while t<Tiempo:
  Pcal=np.linalg.solve(Matriz_resolution,Pin[1:-1])
  Pres=np.concatenate(([Piz],Pcal,[Pder]))
  Pin=Pres
  t=t+DT


LinAlgError: ignored